// Docker live authorization check: independent sessions, cancellation and client feature gates.
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp, mkdir, open, readFile, rm } from 'node:fs/promises';
import { chromium } from 'playwright-core';
import { createToken } from './token-fixture.mjs';
const root = await mkdtemp('/tmp/elsewhere-token-live-');
await mkdir(root + '/runtime', { mode: 0o700 });
const log = await open(root + '/server.log', 'w');
const origin = 'http://127.0.0.1:18446';
const binary = process.env.ELSEWHERE_BINARY || '/src/target/release/elsewhere';
const server = spawn(binary, ['--no-audio', '--no-rtc', '--no-tls', '--render-node', 'none', '--codecs', 'vp8', '--listen', '127.0.0.1:18446', '--screen-size', '320x240'], {
  cwd: root, env: { ...process.env, HOME: root, SHELL: '/bin/bash', XDG_CONFIG_HOME: root + '/config', XDG_CACHE_HOME: root + '/cache', XDG_RUNTIME_DIR: root + '/runtime' }, stdio: ['ignore', log.fd, log.fd],
});
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
const wait = async (label, condition) => { for (let i = 0; i < 200; i++) { if (await condition()) return; await delay(25); } throw Error(label + ' timed out'); };
const request = (path, token, method = 'GET', body) => fetch(origin + path, { method, headers: { Authorization: 'Bearer ' + token, 'Content-Type': 'application/json' }, ...(body !== undefined && { body: JSON.stringify(body) }) });
let admin, browser;
const sockets = [];
const create = async (permissions, expires_at_ms) => {
  const response = await request('/api/tokens', admin, 'POST', { label: 'Live fixture', permissions, expires_at_ms });
  assert.equal(response.status, 201);
  return response.json();
};
const revoke = async token => { const response = await request('/api/tokens/' + token.metadata.id, admin, 'DELETE'); assert.equal(response.status, 204); };
async function connect(token, terminal = false, windowId = null) {
  const socket = new WebSocket(origin.replace('http', 'ws') + (terminal ? '/ws/terminal' : windowId === null ? '/ws' : '/ws/window/' + windowId));
  socket.binaryType = 'arraybuffer';
  const state = { socket, packets: [], closed: false };
  sockets.push(socket);
  socket.onmessage = event => state.packets.push(typeof event.data === 'string' ? event.data : Buffer.from(event.data));
  socket.onclose = event => { state.closed = true; state.code = event.code; };
  await wait('socket open', () => socket.readyState === WebSocket.OPEN);
  socket.send(Buffer.concat([Buffer.from([0x80]), Buffer.from(token)]));
  if (!terminal) socket.send(Buffer.from([0x81, ...new TextEncoder().encode(JSON.stringify({ codecs: ["vp8"] }))]));
  return state;
}
try {
  await wait('server', async () => { try { return (await fetch(origin)).ok; } catch { return false; } });
  admin = await createToken(root);
  const a = await create(['desktop.view', 'desktop.control', 'clipboard.write', 'commands.execute']);
  const b = await create(['desktop.view']);
  const mcp = async (token, session, method, params) => fetch(origin + '/mcp', { method: 'POST', headers: { Authorization: 'Bearer ' + token, 'Content-Type': 'application/json', Accept: 'application/json, text/event-stream', ...(session && { 'Mcp-Session-Id': session }) }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params }) });
  const init = { protocolVersion: '2025-03-26', capabilities: {}, clientInfo: { name: 'token-test', version: '1' } };
  const initA = await mcp(a.token, null, 'initialize', init), initB = await mcp(b.token, null, 'initialize', init);
  const sessionA = initA.headers.get('mcp-session-id'), sessionB = initB.headers.get('mcp-session-id');
  assert.ok(sessionA && sessionB);
  await initA.text(); await initB.text();
  assert.equal((await mcp(b.token, sessionA, 'tools/list', {})).status, 403);
  assert.equal((await fetch(origin + '/mcp', { headers: { Authorization: 'Bearer ' + b.token, Accept: 'text/event-stream', 'Mcp-Session-Id': sessionA, 'Last-Event-ID': '0' } })).status, 403);
  const ownTools = await mcp(b.token, sessionB, 'tools/list', {});
  assert.equal(ownTools.status, 200); await ownTools.text();
  const one = await connect(a.token), two = await connect(b.token);
  await wait('two streams', () => [one, two].every(s => s.packets.some(p => p[0] === 1)));
  const terminal = await connect(a.token, true);
  await wait('terminal output', () => terminal.packets.length > 0);
  const clipboard = await request('/api/clipboard', a.token, 'PUT', 'private text');
  assert.equal(clipboard.status, 202);
  await delay(150);
  assert.ok(two.packets.every(p => ![5, 7, 10, 15, 16].includes(p[0])), 'desktop-only token has no clipboard or audio packets');
  await request('/api/control', a.token, 'POST', { op: 'spawn', cmd: 'stdbuf -oL wev > held-input.log' });
  let heldWindow;
  await wait('input observer', async () => { heldWindow = (await (await request('/api/windows', admin)).json()).find(w => w.app_id === 'wev'); return heldWindow; });
  const c = await create(['desktop.view', 'desktop.control']);
  const windowSession = await connect(c.token, false, heldWindow.id);
  await wait('window stream', () => windowSession.packets.some(p => p[0] === 1));
  windowSession.socket.send(Buffer.from([0x87, 30, 0, 1]));
  const heldLog = () => readFile(root + '/held-input.log', 'utf8');
  await wait('window holds key', async () => (await heldLog()).includes('state: 1 (pressed)'));
  const hidden = await create([]);
  const hiddenExisting = await connect(hidden.token, false, heldWindow.id), hiddenMissing = await connect(hidden.token, false, 999999);
  await wait('window visibility denied', () => hiddenExisting.closed && hiddenMissing.closed);
  assert.equal(hiddenExisting.code, 4001); assert.equal(hiddenMissing.code, 4001);
  await revoke(a);
  await delay(100);
  assert.ok(!(await heldLog()).includes('state: 0 (released)'), 'controller revocation preserves another window token’s held key');
  await revoke(c);
  await wait('held key released by its owner revocation', async () => (await heldLog()).includes('state: 0 (released)'));
  assert.equal((await mcp(a.token, sessionA, 'tools/list', {})).status, 401);
  const otherTools = await mcp(b.token, sessionB, 'tools/list', {}); assert.equal(otherTools.status, 200); await otherTools.text();
  await wait('revoked desktop and terminal', () => one.closed && terminal.closed);
  assert.equal(one.code, 4001);
  assert.equal(two.closed, false);
  assert.equal((await request('/api/me', b.token)).status, 200);
  const deniedTerminal = await connect(b.token, true);
  await wait('terminal permission denied', () => deniedTerminal.closed);
  const expiring = await create(['desktop.view'], Date.now() + 750);
  const timed = await connect(expiring.token);
  await wait('expiry stream', () => timed.packets.some(p => p[0] === 1));
  await wait('idle expiry', () => timed.closed);
  assert.equal(two.closed, false);
  const uploadToken = await create(['files.upload']);
  let uploadBody;
  const upload = fetch(origin + '/api/files/incomplete?path=@transfer', { method: 'PUT', headers: { Authorization: 'Bearer ' + uploadToken.token }, duplex: 'half',
    body: new ReadableStream({ start(controller) { uploadBody = controller; controller.enqueue(new Uint8Array(65536)); } }),
  }).catch(error => error);
  await delay(100);
  await revoke(uploadToken);
  try { uploadBody.close(); } catch {}
  const uploadResult = await upload;
  assert.ok(uploadResult instanceof Error || uploadResult.status === 401);
  assert.equal((await request('/api/files/incomplete?path=@transfer', admin)).status, 404);
  // A committed revoke owns cleanup even when its manager expires while SQLite is busy.
  const victim = await create(['desktop.view']);
  const victimSocket = await connect(victim.token);
  await wait('victim stream', () => victimSocket.packets.some(p => p[0] === 1));
  const manager = await create(['tokens.manage'], Date.now() + 700);
  const lock = spawn('python3', ['-u', '-c', "import sqlite3,sys; db=sqlite3.connect(sys.argv[1]); db.execute('BEGIN IMMEDIATE'); print('locked',flush=True); sys.stdin.readline(); db.rollback()", root + '/config/elsewhere/state.sqlite3']);
  await new Promise(resolve => lock.stdout.once('data', resolve));
  const deleting = request('/api/tokens/' + victim.metadata.id, manager.token, 'DELETE');
  await delay(1000);
  lock.stdin.end('\n');
  await deleting;
  await wait('committed cleanup after caller expiry', () => victimSocket.closed);
  assert.equal((await request('/api/me', victim.token)).status, 401);
  assert.equal(two.closed, false);
  // Registration overlapping revocation cannot leave a live stream.
  const racing = await create(['desktop.view']);
  const attempts = await Promise.all(Array.from({ length: 8 }, () => connect(racing.token)));
  await revoke(racing);
  await wait('registration cancellation', () => attempts.every(s => s.closed));
  assert.equal(two.closed, false);
  browser = await chromium.launch({ executablePath: '/usr/bin/chromium', headless: true, args: ['--no-sandbox'] });
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(origin + '/#token=' + b.token);
  await page.waitForFunction(() => elsewhere.store.get().status === 'connected');
  for (const selector of ['#apps-toggle', '#terminal-toggle', '#power-toggle', '#clipboard-toggle', '#session-mixer-toggle']) assert.equal(await page.locator(selector).count(), 0, selector);
  const writable = await create(['desktop.view', 'clipboard.write', 'files.upload']);
  const writer = await browser.newPage();
  writer.on('pageerror', error => errors.push(error.message));
  await writer.goto(origin + '/#token=' + writable.token);
  await writer.waitForFunction(() => elsewhere.store.get().status === 'connected');
  await writer.locator('#clipboard-toggle').click();
  await writer.getByRole('button', { name: 'New text', exact: true }).click();
  await writer.getByRole('textbox', { name: 'Clipboard text' }).fill('write without read');
  await writer.getByRole('button', { name: 'Save', exact: true }).click();
  await writer.getByRole('button', { name: 'New text', exact: true }).waitFor();
  await writer.getByRole('button', { name: 'Close clipboard', exact: true }).click();
  await writer.locator('canvas.stage').evaluate(canvas => {
    const data = new DataTransfer(); data.items.add(new File(['pasted without browsing'], 'paste-only.txt'));
    canvas.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }));
  });
  await wait('file paste without browsing or desktop control', async () => (await (await request('/api/clipboard', admin)).text()).includes('paste-only.txt'));
  const dropper = await create(['desktop.view', 'desktop.control', 'dragdrop.upload', 'files.upload']);
  const dropSocket = await connect(dropper.token);
  await wait('drop controller', () => dropSocket.packets.some(p => p[0] === 8 && p[1] === 2));
  const batch = crypto.randomUUID();
  assert.equal((await fetch(origin + '/api/drop/' + batch + '/dropped.txt', { method: 'PUT', headers: { Authorization: 'Bearer ' + dropper.token }, body: 'drop without browsing' })).status, 201);
  const drag = message => dropSocket.socket.send(Buffer.concat([Buffer.from([0x90]), Buffer.from(JSON.stringify(message))]));
  drag({ op: 'start' }); drag({ op: 'drop', batch, names: ['dropped.txt'] });
  await wait('drop without file browser', () => dropSocket.packets.some(p => p[0] === 0x13 && JSON.parse(p.subarray(1)).batch === batch));
  assert.equal((await request('/api/files?path=@transfer', dropper.token)).status, 403);
  assert.equal((await request('/api/files/dropped.txt?path=@transfer', admin)).status, 200);
  await revoke(dropper);
  assert.deepEqual(errors, []);
  await revoke(b);
  await page.waitForFunction(() => elsewhere.store.get().status === 'unauthorized');
  await writer.waitForFunction(() => elsewhere.store.get().status === 'connected');
  console.log('Live streams, terminal and transfer cancellation, expiry, SQLite contention, registration races and browser permissions passed');
} catch (error) {
  console.error(await readFile(root + '/server.log', 'utf8'));
  throw error;
} finally {
  await browser?.close();
  for (const socket of sockets) socket.close();
  server.kill('SIGTERM');
  await new Promise(resolve => server.once('exit', resolve));
  await log.close();
  await rm(root, { recursive: true, force: true });
}
