// Docker: dbus-run-session -- node checks/workspaces.mjs
import assert from 'node:assert/strict';
import { spawn, execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { chromium } from 'playwright-core';
import { AUTH, HELLO, VIDEO, WORKSPACES, ROLE, CONTROL, KEY, NOTICE, MOTION_ABS, ROSTER, PASTE_CLIPBOARD } from '../src/protocol.js';
const exec = promisify(execFile);
import { mkdtemp, mkdir, open, readFile, writeFile, rm } from 'node:fs/promises';
import { createToken } from './token-fixture.mjs';
const root = await mkdtemp('/tmp/elsewhere-workspaces-');
await mkdir(root + '/runtime', { mode: 0o700 });
const log = await open(root + '/server.log', 'w');
const origin = 'http://127.0.0.1:18454';
const server = spawn(process.env.ELSEWHERE_BINARY || '/src/target/release/elsewhere',
  ['--no-audio', '--no-rtc', '--no-tls', '--render-node', 'none', '--codecs', 'vp8', '--listen', '127.0.0.1:18454', '--screen-size', '800x600'],
  { cwd: root, env: { ...process.env, HOME: root, SHELL: '/bin/bash', XDG_CONFIG_HOME: root + '/config', XDG_RUNTIME_DIR: root + '/runtime' }, stdio: ['ignore', log.fd, log.fd] });
let token, browser;
const sockets = [];
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
const cpu = async () => { const stat = (await readFile(`/proc/${server.pid}/stat`, 'utf8')).split(') ')[1].trim().split(/\s+/); return Number(stat[11]) + Number(stat[12]); };
const clockTicks = Number((await exec('getconf', ['CLK_TCK'])).stdout.trim());
const request = (path, method = 'GET', body, auth = token) => fetch(origin + path, { method, headers: { Authorization: 'Bearer ' + auth, 'Content-Type': 'application/json' }, ...(body !== undefined && { body: JSON.stringify(body) }) });
const api = async (...args) => { const res = await request(...args); assert.equal(res.status, 200, await res.clone().text()); return res.json(); };
const wait = async (label, fn) => { for (let i = 0; i < 100; i++) { if (await fn()) return; await new Promise(r => setTimeout(r, 50)); } throw Error(label + ' timed out'); };
const control = async body => { const res = await request('/api/control', 'POST', body); assert.equal(res.status, 202, await res.text()); };
const switchTo = async workspace => { await control({ op: 'switchworkspace', workspace }); await wait('workspace ' + workspace, async () => (await api('/api/workspaces')).active === workspace); };
const windows = () => api('/api/windows');
const info = async id => (await windows()).find(w => w.id === id);
const snapshot = async id => { const response = await request(id ? `/api/windows/${id}/snapshot.png` : '/api/screenshot.png'); assert.equal(response.status, 200, await response.clone().text().then(s => s.slice(0, 80))); return Buffer.from(await response.arrayBuffer()); };
const connect = async (window, auth = token) => {
  const socket = new WebSocket(origin.replace('http', 'ws') + (window ? '/ws/window/' + window : '/ws'));
  socket.binaryType = 'arraybuffer';
  const client = { socket, frames: 0, notices: [] }; sockets.push(client);
  socket.onmessage = ({ data }) => {
    const bytes = new Uint8Array(data);
    if (bytes[0] === VIDEO) client.frames++;
    if (bytes[0] === ROLE) client.role = bytes[1];
    if (bytes[0] === ROSTER) client.roster = JSON.parse(new TextDecoder().decode(bytes.subarray(1)));
    if (bytes[0] === WORKSPACES) client.workspaces = JSON.parse(new TextDecoder().decode(bytes.subarray(1)));
    if (bytes[0] === NOTICE) client.notices.push(new TextDecoder().decode(bytes.subarray(1)));
  };
  await wait('websocket', () => socket.readyState === WebSocket.OPEN);
  socket.send(new Uint8Array([AUTH, ...new TextEncoder().encode(auth)]));
  socket.send(new Uint8Array([HELLO, ...new TextEncoder().encode(JSON.stringify({ codecs: ['vp8'] }))]));
  await wait('workspace replay', () => client.workspaces);
  return client;
};
const sendControl = (client, command) => client.socket.send(new Uint8Array([CONTROL, ...new TextEncoder().encode(JSON.stringify(command))]));
try {
  await wait('server', async () => { try { return (await fetch(origin)).ok; } catch { return false; } });
  token = await createToken(root);
  assert.deepEqual(await api('/api/workspaces'), { active: 1, workspaces: [{ id: 1, name: '1' }] });
  await control({ op: 'createworkspace', name: 'Research α' });
  await wait('named creation', async () => (await api('/api/workspaces')).workspaces.some(w => w.id === 2 && w.name === 'Research α'));
  await control({ op: 'renameworkspace', workspace: 2, name: '2' });
  for (let id = 3; id <= 4; id++) {
    await control({ op: 'createworkspace' });
    await wait('additional workspace', async () => (await api('/api/workspaces')).workspaces.some(w => w.id === id));
  }
  const empty = await snapshot();
  const ids = [];
  for (let workspace = 1; workspace <= 4; workspace++) {
    await switchTo(workspace);
    await control({ op: 'spawn', cmd: `foot --title=Workspace${workspace} sh -c 'printf "Workspace ${workspace}\\n"; sleep 1000'` });
    let window;
    await wait('new window', async () => { window = (await windows()).find(w => w.title === `Workspace${workspace}`); return window?.w > 0 && window.focused; });
    assert.equal(window.workspace, workspace);
    ids.push(window.id);
  }
  for (let workspace = 1; workspace <= 4; workspace++) {
    await switchTo(workspace);
    await wait('restored focus', async () => (await info(ids[workspace - 1])).focused);
    for (const window of await windows()) {
      assert.equal(window.minimized, false);
      if (window.workspace !== workspace) assert.equal(window.focused, false);
      await snapshot(window.id);
    }
  }
  const first = await info(ids[0]);
  await control({ op: 'movetoworkspace', id: first.id, workspace: 3 });
  await wait('move', async () => (await info(first.id)).workspace === 3);
  const moved = await info(first.id);
  assert.deepEqual([moved.x, moved.y, moved.w, moved.h], [first.x, first.y, first.w, first.h]);
  assert.equal((await request('/api/input', 'POST', { type: 'click', window: first.id, x: 20, y: 20 })).status, 202);
  assert.equal((await api('/api/workspaces')).active, 4);
  await control({ op: 'activate', id: first.id });
  await wait('cross-workspace activation', async () => (await api('/api/workspaces')).active === 3 && (await info(first.id)).focused);
  await control({ op: 'minimize', id: first.id });
  await wait('minimize', async () => (await info(first.id)).minimized);
  await control({ op: 'movetoworkspace', id: first.id, workspace: 2 });
  await wait('minimized move', async () => { const w = await info(first.id); return w.workspace === 2 && w.minimized; });
  await control({ op: 'activate', id: first.id });
  await wait('restore on destination', async () => (await api('/api/workspaces')).active === 2 && !(await info(first.id)).minimized && (await info(first.id)).focused);
  await control({ op: 'fullscreen', id: first.id });
  await wait('fullscreen', async () => (await info(first.id)).fullscreen);
  await switchTo(1);
  assert.deepEqual(await snapshot(), empty, 'inactive fullscreen and ordinary windows leave an empty desktop');
  await control({ op: 'spawn', cmd: `GDK_BACKEND=x11 python3 /src/web/checks/semantic-elements-native.py gtk ${root}/x11.json` });
  let x11;
  await wait('X11 window', async () => { x11 = (await windows()).find(w => w.x11); return x11?.w > 0; }).catch(async error => { console.error('X11 discovery:', await windows()); throw error; });
  assert.equal(x11.workspace, 1);
  await control({ op: 'movetoworkspace', id: x11.id, workspace: 4 });
  await wait('X11 move', async () => (await info(x11.id)).workspace === 4);
  await snapshot(x11.id);
  await control({ op: 'activate', id: x11.id });
  await wait('X11 activation', async () => (await api('/api/workspaces')).active === 4 && (await info(x11.id)).focused);
  const resizedStream = await connect(first.id);
  for (const [width, height] of [[1000, 700], [800, 600]]) {
    assert.equal((await request('/api/display', 'PATCH', { resolution: { mode: 'fixed', width, height } })).status, 200);
    await wait('inactive fullscreen output resize', async () => { const w = await info(first.id); return w.w === width && w.h === height && w.workspace === 2; });
    await snapshot(first.id);
  }
  resizedStream.socket.close();
  await wait('resize stream closed', () => resizedStream.socket.readyState === WebSocket.CLOSED);
  sockets.splice(sockets.indexOf(resizedStream), 1);
  await control({ op: 'spawn', cmd: `GDK_BACKEND=x11 python3 /src/web/checks/workspace-native.py ${root}/xtransient X11WorkspaceParent` });
  let xParent;
  await wait('X11 transient parent', async () => { xParent = (await windows()).find(w => w.title === 'X11WorkspaceParent'); return xParent?.focused; });
  await writeFile(root + '/xtransient.command', 'tooltip');
  await wait('X11 tooltip', async () => JSON.parse(await readFile(root + '/xtransient.json', 'utf8')).tooltip_frame);
  await delay(150);
  assert.equal((await info(xParent.id)).focused, true, 'X11 tooltip leaves parent focused');
  await writeFile(root + '/xtransient.command', 'close-tooltip');
  await delay(100);
  await control({ op: 'movetoworkspace', id: xParent.id, workspace: 1 });
  await wait('hidden X11 parent', async () => (await info(xParent.id)).workspace === 1);
  await writeFile(root + '/xtransient.command', 'dialog');
  let xDialog;
  await wait('hidden X11 transient', async () => { xDialog = (await windows()).find(w => w.title === 'X11WorkspaceParent Dialog'); return xDialog?.workspace === 1; });
  assert.equal(xDialog.focused, false); assert.equal((await api('/api/workspaces')).active, 4);
  await control({ op: 'movetoworkspace', id: xDialog.id, workspace: 2 });
  await wait('X11 family move', async () => (await info(xParent.id)).workspace === 2 && (await info(xDialog.id)).workspace === 2);
  await control({ op: 'close', id: xParent.id });
  await wait('hidden X11 family destruction', async () => !(await info(xParent.id)) && !(await info(xDialog.id)));
  assert.equal((await api('/api/workspaces')).active, 4);
  for (const invalid of [0, 5, 4294967295]) assert.equal((await request('/api/control', 'POST', { op: 'switchworkspace', workspace: invalid })).status, 400);
  await control({ op: 'spawn', cmd: `GDK_BACKEND=wayland python3 /src/web/checks/workspace-native.py ${root}/native WorkspaceAnimation` });
  let animated;
  await wait('animated window', async () => { animated = (await windows()).find(w => w.title === 'WorkspaceAnimation'); return animated?.w > 0; });
  const native = async () => JSON.parse(await readFile(root + '/native.json', 'utf8'));
  await wait('animation', async () => (await native()).frames > 3);
  await control({ op: 'movetoworkspace', id: animated.id, workspace: 2 });
  await wait('hidden animation', async () => (await info(animated.id)).workspace === 2);
  await delay(400); const idle = (await native()).frames; await delay(400);
  assert((await native()).frames - idle < 3, 'uncaptured hidden window does not keep requesting frames');
  const desktop = await connect();
  const stream = await connect(animated.id);
  await wait('hidden stream animation', () => stream.frames > 3);
  const hiddenBefore = await snapshot(animated.id);
  const nativeBefore = (await native()).frames;
  await delay(500);
  assert((await native()).frames > nativeBefore + 2);
  assert.notDeepEqual(await snapshot(animated.id), hiddenBefore);
  await delay(300); const desktopFrames = desktop.frames, hiddenFrames = stream.frames, cpuBefore = await cpu();
  await delay(700);
  console.log('Inactive captured animation: window frames', stream.frames - hiddenFrames, 'desktop frames', desktop.frames - desktopFrames, 'server CPU seconds', ((await cpu()) - cpuBefore) / clockTicks);
  assert(stream.frames > hiddenFrames + 2); assert(desktop.frames - desktopFrames < 3);
  sendControl(stream, { op: 'focus', id: animated.id });
  await wait('hidden focus before launch', async () => (await info(animated.id)).focused);
  await control({ op: 'spawn', cmd: `GDK_BACKEND=wayland python3 /src/web/checks/workspace-native.py ${root}/visible WorkspaceVisible` });
  let visible;
  await wait('visible input owner', async () => { visible = (await windows()).find(w => w.title === 'WorkspaceVisible'); return visible?.w > 0; });
  const visibleState = async () => JSON.parse(await readFile(root + '/visible.json', 'utf8'));
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 1]));
  await wait('visible held key', async () => (await visibleState()).keys.length === 1);
  assert((await info(visible.id)).focused, 'desktop keys focus newly launched window after inactive input');
  await writeFile(root + '/native.command', 'dialog');
  let dialog;
  await wait('hidden transient', async () => { dialog = (await windows()).find(w => w.title === 'WorkspaceAnimation Dialog'); return dialog?.workspace === 2; });
  assert.equal((await api('/api/workspaces')).active, 4); assert.equal(dialog.focused, false);
  await delay(200);
  assert.equal((await info(visible.id)).focused, true, 'hidden dialog preserves visible focus');
  assert.equal((await visibleState()).keys.length, 1, 'hidden dialog does not release visible held keys');
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 0]));
  await wait('visible key release', async () => (await visibleState()).keys.length === 0);
  sendControl(stream, { op: 'focus', id: animated.id });
  await wait('hidden focus before desktop paste', async () => (await info(animated.id)).focused);
  await wait('paste epoch', () => desktop.roster?.epoch);
  const paste = Buffer.alloc(14); paste[0] = PASTE_CLIPBOARD; paste[1] = 1; paste.writeBigUInt64LE(BigInt(desktop.roster.epoch), 2); paste.writeUInt32LE(1, 10);
  desktop.socket.send(Buffer.concat([paste, await snapshot(animated.id)]));
  await wait('desktop paste reaches visible client', async () => (await visibleState()).events.some(e => e[0] === 'key' && e[1] === 55 && e[2]));
  assert.equal((await api('/api/workspaces')).active, 4);
  await control({ op: 'spawn', cmd: `GDK_BACKEND=wayland python3 /src/web/checks/workspace-native.py ${root}/layer WorkspaceLauncher --layer` });
  const layerState = async () => { try { return JSON.parse(await readFile(root + '/layer.json', 'utf8')); } catch { return null; } };
  await wait('exclusive launcher', async () => (await layerState())?.frames > 2);
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 1]));
  await wait('launcher held key', async () => (await layerState()).keys.length === 1);
  await control({ op: 'movetoworkspace', id: visible.id, workspace: 1 });
  await wait('underlying window moved', async () => (await info(visible.id)).workspace === 1);
  await delay(100);
  assert.equal((await layerState()).keys.length, 1, 'moving underlying window preserves launcher held keys');
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 0]));
  await wait('launcher retains keyboard focus', async () => (await layerState()).keys.length === 0);
  assert.equal((await visibleState()).keys.length, 0);
  assert.equal((await request('/api/input', 'POST', { type: 'click', button: 'right', x: 400, y: 300 })).status, 202);
  await wait('layer menu open', async () => (await layerState()).menu_opened === 1);
  await switchTo(1);
  await wait('switch dismisses layer menu', async () => (await layerState()).menu_closed === 1);
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 1]));
  await wait('launcher focus across switch', async () => (await layerState()).keys.length === 1);
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 0]));
  await wait('launcher key release after switch', async () => (await layerState()).keys.length === 0);
  await switchTo(4);
  sendControl(stream, { op: 'focus', id: animated.id });
  await wait('inactive viewer focus with exclusive layer', async () => (await info(animated.id)).focused);
  await delay(200);
  stream.socket.send(new Uint8Array([KEY, 30, 0, 1]));
  await wait('inactive viewer key while layer commits', async () => (await native()).keys.length === 1);
  assert.equal((await layerState()).keys.length, 0);
  stream.socket.send(new Uint8Array([KEY, 30, 0, 0]));
  await wait('inactive viewer key released', async () => (await native()).keys.length === 0);
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 1]));
  await wait('desktop restores exclusive layer', async () => (await layerState()).keys.length === 1);
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 0]));
  await wait('restored layer key released', async () => (await layerState()).keys.length === 0);
  await writeFile(root + '/layer.command', 'close');
  await delay(150);
  await control({ op: 'activate', id: x11.id });
  await wait('saved displayed focus before launch', async () => (await info(x11.id)).focused);
  sendControl(stream, { op: 'focus', id: animated.id });
  await wait('hidden focus before delayed launch', async () => (await info(animated.id)).focused);
  await control({ op: 'spawn', cmd: `GDK_BACKEND=wayland python3 /src/web/checks/workspace-native.py ${root}/startup WorkspaceStartup --delayed` });
  await wait('startup pending buffer', async () => { try { return await readFile(root + '/startup.waiting', 'utf8'); } catch { return false; } });
  const startupMotion = new Uint8Array(9), coords = new DataView(startupMotion.buffer); startupMotion[0] = MOTION_ABS; coords.setFloat32(1, 100, true); coords.setFloat32(5, 100, true); desktop.socket.send(startupMotion);
  await delay(100);
  await writeFile(root + '/startup.resume', 'draw');
  let startup;
  await wait('startup receives focus after pointer return', async () => { startup = (await windows()).find(w => w.title === 'WorkspaceStartup'); return startup?.focused; });
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 1]));
  await wait('startup receives key', async () => JSON.parse(await readFile(root + '/startup.json', 'utf8')).keys.length === 1);
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 0]));
  await control({ op: 'close', id: startup.id });
  await control({ op: 'spawn', cmd: `GDK_BACKEND=wayland python3 /src/web/checks/workspace-native.py ${root}/delayed WorkspaceDelayed --delayed` });
  await wait('delayed first draw', async () => { try { return await readFile(root + '/delayed.waiting', 'utf8'); } catch { return false; } });
  await wait('pending delayed toplevel', async () => (await windows()).some(w => w.title === 'WorkspaceDelayed'));
  await control({ op: 'activate', id: x11.id });
  await wait('focus while client is loading', async () => (await info(x11.id)).focused);
  await writeFile(root + '/delayed.resume', 'draw');
  let delayed;
  await wait('delayed window drawn', async () => { delayed = (await windows()).find(w => w.title === 'WorkspaceDelayed'); return delayed?.w > 0; });
  await delay(200);
  assert.equal((await info(x11.id)).focused, true, 'late first buffer preserves subsequent focus choice');
  await control({ op: 'close', id: delayed.id });
  await control({ op: 'close', id: visible.id });
  await wait('visible fixture closed', async () => !(await info(visible.id)));

  await control({ op: 'movetoworkspace', id: dialog.id, workspace: 3 });
  await wait('transient family move', async () => (await info(animated.id)).workspace === 3 && (await info(dialog.id)).workspace === 3);
  await control({ op: 'activate', id: animated.id });
  await wait('native focus', async () => (await info(animated.id)).focused);
  const key = new Uint8Array([KEY, 30, 0, 1]);
  stream.socket.send(key);
  await wait('held native key', async () => (await native()).keys.length === 1);
  await switchTo(4);
  await wait('released held native key', async () => (await native()).keys.length === 0);
  stream.socket.send(key);
  await wait('window stream key on separate workspace', async () => (await native()).keys.length === 1);
  assert.equal((await api('/api/workspaces')).active, 4);
  stream.socket.send(new Uint8Array([KEY, 30, 0, 0]));
  await wait('released stream key', async () => (await native()).keys.length === 0);
  const motion = (x, y) => { const b = new Uint8Array(9), dv = new DataView(b.buffer); b[0] = 0x83; dv.setFloat32(1, x, true); dv.setFloat32(5, y, true); stream.socket.send(b); };
  const button = (code, pressed) => stream.socket.send(new Uint8Array([0x85, code & 255, code >> 8, Number(pressed)]));
  sendControl(stream, { op: 'focus', id: animated.id });
  const beforeMove = await info(animated.id);
  motion(30, 30); button(0x112, true);
  await wait('native move request', async () => (await native()).move_requested === 1);
  await delay(50); motion(80, 60);
  await wait('inactive client move', async () => (await info(animated.id)).x > beforeMove.x);
  button(0x112, false); await delay(50);
  const beforeResize = await info(animated.id);
  motion(8, 8); button(0x110, true);
  await wait('native resize request', async () => (await native()).resize_requested === 1);
  await delay(50); motion(68, 48);
  await wait('inactive client resize', async () => (await info(animated.id)).w > beforeResize.w);
  button(0x110, false); await delay(50);
  await control({ op: 'minimize', id: animated.id });
  await wait('input workspace fallback', async () => (await info(dialog.id)).focused);
  assert.equal((await api('/api/workspaces')).active, 4);
  await control({ op: 'unminimize', id: animated.id });
  sendControl(stream, { op: 'focus', id: animated.id });
  await writeFile(root + '/native.command', 'loose');
  let loose;
  await wait('independent future child', async () => { loose = (await windows()).find(w => w.title === 'WorkspaceAnimation Loose'); return loose?.workspace === 4 && loose.w > 0; });
  await control({ op: 'move', id: loose.id, x: 500, y: 380 });
  await wait('child placement', async () => (await info(loose.id)).x === 500);
  assert.equal((await request('/api/input', 'POST', { type: 'click', x: 799, y: 599 })).status, 202);
  await wait('unfocused child', async () => !(await info(loose.id)).focused);
  assert.equal((await request('/api/input', 'POST', { type: 'move', x: 550, y: 420 })).status, 202);
  await delay(100);
  await writeFile(root + '/native.command', 'adopt');
  await wait('parent-driven move', async () => (await info(loose.id)).workspace === 3);
  const childEvents = (await native()).child_events;
  assert.equal((await request('/api/input', 'POST', { type: 'scroll', dx: 0, dy: 1 })).status, 202);
  assert.equal((await request('/api/input', 'POST', { type: 'button', button: 'left', pressed: true })).status, 202);
  assert.equal((await request('/api/input', 'POST', { type: 'button', button: 'left', pressed: false })).status, 202);
  await delay(150); assert.equal((await native()).child_events, childEvents, 'parent change invalidates the hovered hidden child before wheel/button input');
  const readKey = await createToken(root, ['desktop.view']);
  const writeKey = await createToken(root, ['desktop.control']);
  for (const op of ['createworkspace', 'renameworkspace']) {
    assert.equal((await request('/api/control', 'POST', { op, workspace: 1, name: 'Denied' }, readKey)).status, 403);
    for (const name of ['x'.repeat(257), 'α'.repeat(129), 'bad\nname']) {
      assert.equal((await request('/api/control', 'POST', { op, workspace: 1, name })).status, 400);
    }
  }
  assert.equal((await request('/api/control', 'POST', { op: 'renameworkspace', workspace: 1, name: '  ' })).status, 400);
  assert.equal((await request('/api/control', 'POST', { op: 'renameworkspace', workspace: 99999, name: 'Missing' })).status, 400);
  assert.equal((await request('/api/workspaces', 'GET', undefined, writeKey)).status, 403);
  assert.equal((await request('/api/control', 'POST', { op: 'switchworkspace', workspace: 1 }, readKey)).status, 403);
  assert.equal((await request('/api/control', 'POST', { op: 'switchworkspace', workspace: 1 }, writeKey)).status, 202);
  await wait('control-only HTTP switch', async () => (await api('/api/workspaces')).active === 1);
  await switchTo(4);
  const mcp = async auth => {
    let session, sequence = 0;
    const rpc = (method, params, notify = false) => fetch(origin + '/mcp', { method: 'POST', headers: { Authorization: 'Bearer ' + auth, 'Content-Type': 'application/json', Accept: 'application/json, text/event-stream', ...(session && { 'Mcp-Session-Id': session }) }, body: JSON.stringify({ jsonrpc: '2.0', ...(!notify && { id: ++sequence }), method, params }) });
    const init = await rpc('initialize', { protocolVersion: '2025-03-26', capabilities: {}, clientInfo: { name: 'workspace-check', version: '1' } });
    session = init.headers.get('mcp-session-id'); assert(session); await init.text();
    await (await rpc('notifications/initialized', {}, true)).text();
    return async (name, args = {}) => {
      const body = await (await rpc('tools/call', { name, arguments: args })).text();
      const line = body.split('\n').find(l => l.startsWith('data:') && l.slice(5).trim());
      const response = JSON.parse(line ? line.slice(5) : body);
      assert(response.result, body); return response.result;
    };
  };
  const readMcp = await mcp(readKey), writeMcp = await mcp(writeKey);
  assert(!(await readMcp('workspaces')).isError);
  assert((await readMcp('rename_workspace', { workspace: 1, name: 'Denied' })).isError);
  assert((await writeMcp('rename_workspace', { workspace: 1, name: '' })).isError);
  assert(!(await writeMcp('rename_workspace', { workspace: 1, name: 'MCP name' })).isError);
  await wait('MCP rename', async () => (await api('/api/workspaces')).workspaces[0].name === 'MCP name');
  assert(JSON.stringify(await readMcp('workspaces')).includes('MCP name'));
  await control({ op: 'renameworkspace', workspace: 1, name: '1' });
  assert.equal((await writeMcp('workspaces')).isError, true);
  assert.equal((await readMcp('switch_workspace', { workspace: 1 })).isError, true);
  assert(!(await writeMcp('switch_workspace', { workspace: 1 })).isError);
  await wait('control-only MCP switch', async () => (await api('/api/workspaces')).active === 1);
  assert(!(await writeMcp('move_to_workspace', { window: animated.id, workspace: 2 })).isError);
  await wait('MCP family move', async () => (await info(animated.id)).workspace === 2 && (await info(dialog.id)).workspace === 2);
  assert((await writeMcp('switch_workspace', { workspace: 5 })).isError);
  await control({ op: 'movetoworkspace', id: animated.id, workspace: 3 });
  await switchTo(4);
  const readonly = await connect(undefined, readKey);
  const participant = await connect();
  sendControl(readonly, { op: 'switchworkspace', workspace: 1 });
  sendControl(participant, { op: 'switchworkspace', workspace: 1 });
  sendControl(participant, { op: 'movetoworkspace', id: animated.id, workspace: 1 });
  await delay(150); assert.equal((await api('/api/workspaces')).active, 4); assert.equal((await info(animated.id)).workspace, 1);
  sendControl(participant, { op: 'activate', id: animated.id });
  await wait('participant explicit activation', async () => (await api('/api/workspaces')).active === 1);
  await control({ op: 'movetoworkspace', id: animated.id, workspace: 3 });
  sendControl(stream, { op: 'switchworkspace', workspace: 4 });
  await wait('window socket workspace control', async () => (await api('/api/workspaces')).active === 4);
  const switchStart = Date.now(), framesBeforeSwitch = desktop.frames;
  sendControl(desktop, { op: 'switchworkspace', workspace: 1 });
  await wait('controller switch broadcast', () => sockets.every(s => s.workspaces.active === 1));

  await wait('complete desktop frame after switch', () => desktop.frames > framesBeforeSwitch);
  console.log('Switch-to-desktop-frame ms:', Date.now() - switchStart);

  await exec('wayland-scanner', ['client-header', '/usr/share/wayland-protocols/staging/ext-workspace/ext-workspace-v1.xml', root + '/ext-workspace-v1-client-protocol.h']);
  await exec('wayland-scanner', ['private-code', '/usr/share/wayland-protocols/staging/ext-workspace/ext-workspace-v1.xml', root + '/ext-workspace-v1-protocol.c']);
  await exec('cc', ['-Wall', '-Wextra', '-Werror', '-I' + root, '/src/web/checks/workspace-panel.c', root + '/ext-workspace-v1-protocol.c', '-lwayland-client', '-o', root + '/panel']);
  await control({ op: 'spawn', cmd: `${root}/panel 2 > ${root}/panel.json` });
  await wait('panel protocol activation', async () => { try { return JSON.parse(await readFile(root + '/panel.json', 'utf8')).active === 2; } catch { return false; } });
  assert.deepEqual(JSON.parse(await readFile(root + '/panel.json', 'utf8')), { before: 1, active: 2, count: 4, commit_boundary: true });
  await wait('panel shared state', () => sockets.every(s => s.workspaces.active === 2));
  await control({ op: 'spawn', cmd: `${root}/panel 2 'Panel name' ${root}/rename-ready > ${root}/rename-panel.json` });
  await wait('rename panel ready', async () => { try { return await readFile(root + '/rename-ready', 'utf8'); } catch { return false; } });
  const beforeRename = await windows();
  await control({ op: 'renameworkspace', workspace: 2, name: 'Panel name' });
  await wait('native panel rename event', async () => { try { return JSON.parse(await readFile(root + '/rename-panel.json', 'utf8')).renamed; } catch { return false; } });
  await wait('rename broadcast', () => sockets.every(s => s.workspaces.workspaces.find(w => w.id === 2).name === 'Panel name'));
  assert.equal((await api('/api/workspaces')).active, 2);
  assert.deepEqual((await windows()).map(w => [w.id, w.workspace]), beforeRename.map(w => [w.id, w.workspace]));
  for (const client of sockets) client.socket.close();
  await wait('sockets closed', () => sockets.every(s => s.socket.readyState === WebSocket.CLOSED));

  browser = await chromium.launch({ executablePath: '/usr/bin/chromium', args: ['--no-sandbox'] });
  const page = await browser.newPage({ viewport: { width: 1100, height: 750 } });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(origin + '/#token=' + token);
  await page.waitForFunction(() => elsewhere.store.get().role === 'controller');
  const moveSelector = page.getByRole('combobox', { name: 'Move WorkspaceAnimation to workspace', exact: true });
  await moveSelector.hover();
  assert(await moveSelector.evaluate(el => { const r = el.getBoundingClientRect(); return document.elementFromPoint(r.x + r.width / 2, r.y + r.height / 2) === el; }));
  await moveSelector.selectOption('4');
  await wait('viewer family move', async () => (await info(animated.id)).workspace === 4 && (await info(dialog.id)).workspace === 4);
  await moveSelector.selectOption('3');
  await wait('viewer family move back', async () => (await info(animated.id)).workspace === 3);
  await page.screenshot({ path: root + '/workspace-viewer.png' });
  await page.setViewportSize({ width: 400, height: 750 });
  await page.screenshot({ path: root + '/workspace-narrow.png' });
  const headerFits = await page.locator('header').first().evaluate(el => el.scrollWidth <= el.clientWidth);
  assert(headerFits, 'workspace toolbar fits narrow viewport');
  await page.setViewportSize({ width: 1100, height: 750 });
  await page.getByRole('combobox', { name: 'Workspace', exact: true }).selectOption('1');
  await wait('viewer selector', async () => (await api('/api/workspaces')).active === 1);
  const reader = await browser.newPage();
  await reader.goto(origin + '/#token=' + readKey);
  await reader.waitForFunction(() => elsewhere.store.get().workspaces.active === 1);
  assert(await reader.getByRole('combobox', { name: 'Workspace', exact: true }).isDisabled());
  await page.getByRole('combobox', { name: 'Workspace', exact: true }).selectOption('2');
  await reader.waitForFunction(() => elsewhere.store.get().workspaces.active === 2);
  await reader.reload(); await reader.waitForFunction(() => elsewhere.store.get().workspaces.active === 2);
  assert(await reader.getByText('workspace Panel name', { exact: true }).count() > 0, 'view-only window rows use workspace names');
  await control({ op: 'renameworkspace', workspace: 2, name: 'x'.repeat(256) });
  const namedBadge = reader.getByText('workspace ' + 'x'.repeat(256), { exact: true }).first();
  await namedBadge.waitFor();
  assert(await namedBadge.evaluate(el => el.getBoundingClientRect().width <= el.parentElement.getBoundingClientRect().width), 'long workspace names fit view-only badges');
  await control({ op: 'renameworkspace', workspace: 2, name: 'Panel name' });
  assert.equal(await reader.getByRole('button', { name: 'Rename Workspace', exact: true }).count(), 0);
  assert.equal(await reader.getByRole('button', { name: 'New Workspace', exact: true }).count(), 0);
  const promptAction = async (label, value) => {
    page.once('dialog', dialog => value === null ? dialog.dismiss() : dialog.accept(value));
    await page.getByRole('button', { name: label, exact: true }).click();
  };
  await page.getByRole('combobox', { name: 'Workspace', exact: true }).selectOption('1');
  await wait('starting workspace active', async () => (await api('/api/workspaces')).active === 1);
  const membership = (await windows()).map(w => [w.id, w.workspace]);
  await promptAction('Rename Workspace', 'x'.repeat(256));
  await reader.waitForFunction(() => elsewhere.store.get().workspaces.workspaces[0].name.length === 256);
  assert(await moveSelector.evaluate(el => el.getBoundingClientRect().width <= el.parentElement.getBoundingClientRect().width), 'long workspace names fit the window move control');
  await promptAction('Rename Workspace', 'Main α');
  await reader.waitForFunction(() => elsewhere.store.get().workspaces.workspaces[0].name === 'Main α');
  assert.equal(await page.getByRole('combobox', { name: 'Workspace', exact: true }).locator('option:checked').textContent(), 'Workspace Main α');
  assert((await moveSelector.locator('option').allTextContents()).some(s => s.includes('Main α')));
  assert.equal((await api('/api/workspaces')).active, 1);
  assert.deepEqual((await windows()).map(w => [w.id, w.workspace]), membership);
  assert(JSON.stringify(await readMcp('workspaces')).includes('Main α'));
  await promptAction('New Workspace', null);
  assert.equal((await api('/api/workspaces')).workspaces.length, 4);
  await promptAction('New Workspace', 'Planning β');
  await reader.waitForFunction(() => elsewhere.store.get().workspaces.workspaces.some(w => w.name === 'Planning β'));
  const named = (await api('/api/workspaces')).workspaces.find(w => w.name === 'Planning β');
  assert(named.id > 4);
  assert.equal((await api('/api/workspaces')).active, 1);
  await control({ op: 'deleteworkspace', workspace: named.id });
  await wait('named workspace deletion', async () => (await api('/api/workspaces')).workspaces.length === 4);
  await page.getByRole('combobox', { name: 'Workspace', exact: true }).selectOption('2');
  await wait('viewer restores workspace', async () => (await api('/api/workspaces')).active === 2);
  const popup = await browser.newPage();
  await popup.goto(origin + '/?window=' + animated.id + '#token=' + token);
  await popup.waitForFunction(() => elsewhere.store.get().status === 'connected');
  await popup.bringToFront(); await popup.locator('canvas.stage').click(); await delay(200);
  assert.equal((await api('/api/workspaces')).active, 2, 'window viewer input preserves the shared workspace');
  await control({ op: 'activate', id: animated.id });
  await wait('explicit activation', async () => (await api('/api/workspaces')).active === 3);
  for (let i = 0; i < 80; i++) await control({ op: 'createworkspace' });
  await wait('dynamic workspace creation', async () => (await api('/api/workspaces')).workspaces.length === 84);
  const latest = (await api('/api/workspaces')).workspaces.at(-1).id;
  await control({ op: 'movetoworkspace', id: animated.id, workspace: latest });
  await wait('new workspace family move', async () => (await info(dialog.id)).workspace === latest);
  await switchTo(latest);
  await control({ op: 'deleteworkspace', workspace: latest });
  await wait('populated workspace deletion', async () => (await api('/api/workspaces')).active === 1 && (await info(dialog.id)).workspace === 1);
  assert(!(await writeMcp('create_workspace', { name: 'MCP created' })).isError);
  await wait('MCP creation', async () => (await api('/api/workspaces')).workspaces.at(-1).id > latest);
  assert.equal((await api('/api/workspaces')).workspaces.at(-1).name, 'MCP created');
  assert((await readMcp('create_workspace')).isError);
  for (const entry of (await api('/api/workspaces')).workspaces.slice(1)) await control({ op: 'deleteworkspace', workspace: entry.id });
  await wait('one workspace', async () => (await api('/api/workspaces')).workspaces.length === 1);
  assert.equal((await request('/api/control', 'POST', { op: 'deleteworkspace', workspace: 1 })).status, 400);
  assert.deepEqual(errors, []);
  console.log('Panel commit boundaries, shared/replayed viewer state, grants, transient families, held-key release, hidden animated streams, and explicit viewer activation passed.');
  console.log('Dynamic workspaces: placement, focus, movement, minimization, activation, hidden rendering, snapshots, and inactive input passed for Wayland and X11.');
} catch (error) { console.error((await readFile(root + '/server.log', 'utf8')).split('\n').slice(-12).join('\n')); throw error; }
finally {
  for (const client of sockets) client.socket.close();
  await browser?.close();
  if (server.exitCode === null) { server.kill('SIGTERM'); await new Promise(r => server.once('exit', r)); }
  await log.close();
  if (!process.env.KEEP_FIXTURE) await rm(root, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 }); else console.log(root);
}
