// Docker: dbus-run-session -- node checks/workspaces.mjs
import assert from 'node:assert/strict';
import { spawn, execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { chromium } from 'playwright-core';
import { AUTH, HELLO, VIDEO, WORKSPACES, ROLE, CONTROL, KEY, NOTICE } from '../src/protocol.js';
const exec = promisify(execFile);
import { mkdtemp, mkdir, open, readFile, writeFile, rm } from 'node:fs/promises';
import { createToken } from './token-fixture.mjs';
const root = await mkdtemp('/tmp/elsewhere-workspaces-');
await mkdir(root + '/runtime', { mode: 0o700 });
const log = await open(root + '/server.log', 'w');
const origin = 'http://127.0.0.1:18454';
const server = spawn(process.env.ELSEWHERE_BINARY || '/src/target/release/elsewhere',
  ['--no-audio', '--no-rtc', '--no-tls', '--render-node', 'none', '--codecs', 'vp8', '--listen', '127.0.0.1:18454', '--screen-size', '800x600'],
  { cwd: root, env: { ...process.env, HOME: root, SHELL: '/bin/bash', XDG_CONFIG_HOME: root + '/config', XDG_RUNTIME_DIR: root + '/runtime' }, stdio: ['ignore', log.fd, log.fd] });
let token, browser;
const sockets = [];
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
const cpu = async () => { const stat = (await readFile(`/proc/${server.pid}/stat`, 'utf8')).split(') ')[1].trim().split(/\s+/); return Number(stat[11]) + Number(stat[12]); };
const clockTicks = Number((await exec('getconf', ['CLK_TCK'])).stdout.trim());
const request = (path, method = 'GET', body, auth = token) => fetch(origin + path, { method, headers: { Authorization: 'Bearer ' + auth, 'Content-Type': 'application/json' }, ...(body !== undefined && { body: JSON.stringify(body) }) });
const api = async (...args) => { const res = await request(...args); assert.equal(res.status, 200, await res.clone().text()); return res.json(); };
const wait = async (label, fn) => { for (let i = 0; i < 100; i++) { if (await fn()) return; await new Promise(r => setTimeout(r, 50)); } throw Error(label + ' timed out'); };
const control = async body => { const res = await request('/api/control', 'POST', body); assert.equal(res.status, 202, await res.text()); };
const switchTo = async workspace => { await control({ op: 'switchworkspace', workspace }); await wait('workspace ' + workspace, async () => (await api('/api/workspaces')).active === workspace); };
const windows = () => api('/api/windows');
const info = async id => (await windows()).find(w => w.id === id);
const snapshot = async id => { const response = await request(id ? `/api/windows/${id}/snapshot.png` : '/api/screenshot.png'); assert.equal(response.status, 200, await response.clone().text().then(s => s.slice(0, 80))); return Buffer.from(await response.arrayBuffer()); };
const connect = async (window, auth = token) => {
  const socket = new WebSocket(origin.replace('http', 'ws') + (window ? '/ws/window/' + window : '/ws'));
  socket.binaryType = 'arraybuffer';
  const client = { socket, frames: 0, notices: [] }; sockets.push(client);
  socket.onmessage = ({ data }) => {
    const bytes = new Uint8Array(data);
    if (bytes[0] === VIDEO) client.frames++;
    if (bytes[0] === ROLE) client.role = bytes[1];
    if (bytes[0] === WORKSPACES) client.workspaces = JSON.parse(new TextDecoder().decode(bytes.subarray(1)));
    if (bytes[0] === NOTICE) client.notices.push(new TextDecoder().decode(bytes.subarray(1)));
  };
  await wait('websocket', () => socket.readyState === WebSocket.OPEN);
  socket.send(new Uint8Array([AUTH, ...new TextEncoder().encode(auth)]));
  socket.send(new Uint8Array([HELLO, ...new TextEncoder().encode(JSON.stringify({ codecs: ['vp8'] }))]));
  await wait('workspace replay', () => client.workspaces);
  return client;
};
const sendControl = (client, command) => client.socket.send(new Uint8Array([CONTROL, ...new TextEncoder().encode(JSON.stringify(command))]));
try {
  await wait('server', async () => { try { return (await fetch(origin)).ok; } catch { return false; } });
  token = await createToken(root);
  assert.deepEqual(await api('/api/workspaces'), { active: 1, count: 4 });
  const empty = await snapshot();
  const ids = [];
  for (let workspace = 1; workspace <= 4; workspace++) {
    await switchTo(workspace);
    await control({ op: 'spawn', cmd: `foot --title=Workspace${workspace} sh -c 'printf "Workspace ${workspace}\\n"; sleep 1000'` });
    let window;
    await wait('new window', async () => { window = (await windows()).find(w => w.title === `Workspace${workspace}`); return window?.w > 0 && window.focused; });
    assert.equal(window.workspace, workspace);
    ids.push(window.id);
  }
  for (let workspace = 1; workspace <= 4; workspace++) {
    await switchTo(workspace);
    await wait('restored focus', async () => (await info(ids[workspace - 1])).focused);
    for (const window of await windows()) {
      assert.equal(window.minimized, false);
      if (window.workspace !== workspace) assert.equal(window.focused, false);
      await snapshot(window.id);
    }
  }
  const first = await info(ids[0]);
  await control({ op: 'movetoworkspace', id: first.id, workspace: 3 });
  await wait('move', async () => (await info(first.id)).workspace === 3);
  const moved = await info(first.id);
  assert.deepEqual([moved.x, moved.y, moved.w, moved.h], [first.x, first.y, first.w, first.h]);
  assert.equal((await request('/api/input', 'POST', { type: 'click', window: first.id, x: 20, y: 20 })).status, 409);
  assert.equal((await api('/api/workspaces')).active, 4);
  await control({ op: 'activate', id: first.id });
  await wait('cross-workspace activation', async () => (await api('/api/workspaces')).active === 3 && (await info(first.id)).focused);
  await control({ op: 'minimize', id: first.id });
  await wait('minimize', async () => (await info(first.id)).minimized);
  await control({ op: 'movetoworkspace', id: first.id, workspace: 2 });
  await wait('minimized move', async () => { const w = await info(first.id); return w.workspace === 2 && w.minimized; });
  await control({ op: 'activate', id: first.id });
  await wait('restore on destination', async () => (await api('/api/workspaces')).active === 2 && !(await info(first.id)).minimized && (await info(first.id)).focused);
  await control({ op: 'fullscreen', id: first.id });
  await wait('fullscreen', async () => (await info(first.id)).fullscreen);
  await switchTo(1);
  assert.deepEqual(await snapshot(), empty, 'inactive fullscreen and ordinary windows leave an empty desktop');
  await control({ op: 'spawn', cmd: `GDK_BACKEND=x11 python3 /src/web/checks/semantic-elements-native.py gtk ${root}/x11.json` });
  let x11;
  await wait('X11 window', async () => { x11 = (await windows()).find(w => w.x11); return x11?.w > 0; }).catch(async error => { console.error('X11 discovery:', await windows()); throw error; });
  assert.equal(x11.workspace, 1);
  await control({ op: 'movetoworkspace', id: x11.id, workspace: 4 });
  await wait('X11 move', async () => (await info(x11.id)).workspace === 4);
  await snapshot(x11.id);
  await control({ op: 'activate', id: x11.id });
  await wait('X11 activation', async () => (await api('/api/workspaces')).active === 4 && (await info(x11.id)).focused);
  const resizedStream = await connect(first.id);
  for (const [width, height] of [[1000, 700], [800, 600]]) {
    assert.equal((await request('/api/display', 'PATCH', { resolution: { mode: 'fixed', width, height } })).status, 200);
    await wait('inactive fullscreen output resize', async () => { const w = await info(first.id); return w.w === width && w.h === height && w.workspace === 2; });
    await snapshot(first.id);
  }
  resizedStream.socket.close();
  await wait('resize stream closed', () => resizedStream.socket.readyState === WebSocket.CLOSED);
  sockets.splice(sockets.indexOf(resizedStream), 1);
  await control({ op: 'spawn', cmd: `GDK_BACKEND=x11 python3 /src/web/checks/workspace-native.py ${root}/xtransient X11WorkspaceParent` });
  let xParent;
  await wait('X11 transient parent', async () => { xParent = (await windows()).find(w => w.title === 'X11WorkspaceParent'); return xParent?.focused; });
  await writeFile(root + '/xtransient.command', 'tooltip');
  await wait('X11 tooltip', async () => JSON.parse(await readFile(root + '/xtransient.json', 'utf8')).tooltip_frame);
  await delay(150);
  assert.equal((await info(xParent.id)).focused, true, 'X11 tooltip leaves parent focused');
  await writeFile(root + '/xtransient.command', 'close-tooltip');
  await delay(100);
  await control({ op: 'movetoworkspace', id: xParent.id, workspace: 1 });
  await wait('hidden X11 parent', async () => (await info(xParent.id)).workspace === 1);
  await writeFile(root + '/xtransient.command', 'dialog');
  let xDialog;
  await wait('hidden X11 transient', async () => { xDialog = (await windows()).find(w => w.title === 'X11WorkspaceParent Dialog'); return xDialog?.workspace === 1; });
  assert.equal(xDialog.focused, false); assert.equal((await api('/api/workspaces')).active, 4);
  await control({ op: 'movetoworkspace', id: xDialog.id, workspace: 2 });
  await wait('X11 family move', async () => (await info(xParent.id)).workspace === 2 && (await info(xDialog.id)).workspace === 2);
  await control({ op: 'close', id: xParent.id });
  await wait('hidden X11 family destruction', async () => !(await info(xParent.id)) && !(await info(xDialog.id)));
  assert.equal((await api('/api/workspaces')).active, 4);
  for (const invalid of [0, 5, 4294967295]) assert.equal((await request('/api/control', 'POST', { op: 'switchworkspace', workspace: invalid })).status, 400);
  await control({ op: 'spawn', cmd: `GDK_BACKEND=wayland python3 /src/web/checks/workspace-native.py ${root}/native WorkspaceAnimation` });
  let animated;
  await wait('animated window', async () => { animated = (await windows()).find(w => w.title === 'WorkspaceAnimation'); return animated?.w > 0; });
  const native = async () => JSON.parse(await readFile(root + '/native.json', 'utf8'));
  await wait('animation', async () => (await native()).frames > 3);
  await control({ op: 'movetoworkspace', id: animated.id, workspace: 2 });
  await wait('hidden animation', async () => (await info(animated.id)).workspace === 2);
  await delay(400); const idle = (await native()).frames; await delay(400);
  assert((await native()).frames - idle < 3, 'uncaptured hidden window does not keep requesting frames');
  const desktop = await connect();
  const stream = await connect(animated.id);
  await wait('hidden stream animation', () => stream.frames > 3);
  const hiddenBefore = await snapshot(animated.id);
  const nativeBefore = (await native()).frames;
  await delay(500);
  assert((await native()).frames > nativeBefore + 2);
  assert.notDeepEqual(await snapshot(animated.id), hiddenBefore);
  await delay(300); const desktopFrames = desktop.frames, hiddenFrames = stream.frames, cpuBefore = await cpu();
  await delay(700);
  console.log('Inactive captured animation: window frames', stream.frames - hiddenFrames, 'desktop frames', desktop.frames - desktopFrames, 'server CPU seconds', ((await cpu()) - cpuBefore) / clockTicks);
  assert(stream.frames > hiddenFrames + 2); assert(desktop.frames - desktopFrames < 3);
  await control({ op: 'spawn', cmd: `GDK_BACKEND=wayland python3 /src/web/checks/workspace-native.py ${root}/visible WorkspaceVisible` });
  let visible;
  await wait('visible input owner', async () => { visible = (await windows()).find(w => w.title === 'WorkspaceVisible'); return visible?.focused; });
  const visibleState = async () => JSON.parse(await readFile(root + '/visible.json', 'utf8'));
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 1]));
  await wait('visible held key', async () => (await visibleState()).keys.length === 1);
  await writeFile(root + '/native.command', 'dialog');
  let dialog;
  await wait('hidden transient', async () => { dialog = (await windows()).find(w => w.title === 'WorkspaceAnimation Dialog'); return dialog?.workspace === 2; });
  assert.equal((await api('/api/workspaces')).active, 4); assert.equal(dialog.focused, false);
  await delay(200);
  assert.equal((await info(visible.id)).focused, true, 'hidden dialog preserves visible focus');
  assert.equal((await visibleState()).keys.length, 1, 'hidden dialog does not release visible held keys');
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 0]));
  await wait('visible key release', async () => (await visibleState()).keys.length === 0);
  await control({ op: 'spawn', cmd: `GDK_BACKEND=wayland python3 /src/web/checks/workspace-native.py ${root}/layer WorkspaceLauncher --layer` });
  const layerState = async () => { try { return JSON.parse(await readFile(root + '/layer.json', 'utf8')); } catch { return null; } };
  await wait('exclusive launcher', async () => (await layerState())?.frames > 2);
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 1]));
  await wait('launcher held key', async () => (await layerState()).keys.length === 1);
  await control({ op: 'movetoworkspace', id: visible.id, workspace: 1 });
  await wait('underlying window moved', async () => (await info(visible.id)).workspace === 1);
  await delay(100);
  assert.equal((await layerState()).keys.length, 1, 'moving underlying window preserves launcher held keys');
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 0]));
  await wait('launcher retains keyboard focus', async () => (await layerState()).keys.length === 0);
  assert.equal((await visibleState()).keys.length, 0);
  assert.equal((await request('/api/input', 'POST', { type: 'click', button: 'right', x: 400, y: 300 })).status, 202);
  await wait('layer menu open', async () => (await layerState()).menu_opened === 1);
  await switchTo(1);
  await wait('switch dismisses layer menu', async () => (await layerState()).menu_closed === 1);
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 1]));
  await wait('launcher focus across switch', async () => (await layerState()).keys.length === 1);
  desktop.socket.send(new Uint8Array([KEY, 30, 0, 0]));
  await wait('launcher key release after switch', async () => (await layerState()).keys.length === 0);
  await switchTo(4);
  await writeFile(root + '/layer.command', 'close');
  await delay(150);
  await control({ op: 'spawn', cmd: `GDK_BACKEND=wayland python3 /src/web/checks/workspace-native.py ${root}/delayed WorkspaceDelayed --delayed` });
  await wait('delayed first draw', async () => { try { return await readFile(root + '/delayed.waiting', 'utf8'); } catch { return false; } });
  await wait('pending delayed toplevel', async () => (await windows()).some(w => w.title === 'WorkspaceDelayed'));
  await control({ op: 'activate', id: x11.id });
  await wait('focus while client is loading', async () => (await info(x11.id)).focused);
  await writeFile(root + '/delayed.resume', 'draw');
  let delayed;
  await wait('delayed window drawn', async () => { delayed = (await windows()).find(w => w.title === 'WorkspaceDelayed'); return delayed?.w > 0; });
  await delay(200);
  assert.equal((await info(x11.id)).focused, true, 'late first buffer preserves subsequent focus choice');
  await control({ op: 'close', id: delayed.id });
  await control({ op: 'close', id: visible.id });
  await wait('visible fixture closed', async () => !(await info(visible.id)));

  await control({ op: 'movetoworkspace', id: dialog.id, workspace: 3 });
  await wait('transient family move', async () => (await info(animated.id)).workspace === 3 && (await info(dialog.id)).workspace === 3);
  await control({ op: 'activate', id: animated.id });
  await wait('native focus', async () => (await info(animated.id)).focused);
  const key = new Uint8Array([KEY, 30, 0, 1]);
  stream.socket.send(key);
  await wait('held native key', async () => (await native()).keys.length === 1);
  await switchTo(4);
  await wait('released held native key', async () => (await native()).keys.length === 0);
  const events = (await native()).events;
  stream.socket.send(key); await delay(150);
  assert.deepEqual((await native()).events, events);
  assert(stream.notices.some(n => n.includes('inactive workspace')));
  await writeFile(root + '/native.command', 'loose');
  let loose;
  await wait('independent future child', async () => { loose = (await windows()).find(w => w.title === 'WorkspaceAnimation Loose'); return loose?.workspace === 4 && loose.w > 0; });
  await control({ op: 'move', id: loose.id, x: 500, y: 380 });
  await wait('child placement', async () => (await info(loose.id)).x === 500);
  assert.equal((await request('/api/input', 'POST', { type: 'click', x: 799, y: 599 })).status, 202);
  await wait('unfocused child', async () => !(await info(loose.id)).focused);
  assert.equal((await request('/api/input', 'POST', { type: 'move', x: 550, y: 420 })).status, 202);
  await delay(100);
  await writeFile(root + '/native.command', 'adopt');
  await wait('parent-driven move', async () => (await info(loose.id)).workspace === 3);
  const childEvents = (await native()).child_events;
  assert.equal((await request('/api/input', 'POST', { type: 'scroll', dx: 0, dy: 1 })).status, 202);
  assert.equal((await request('/api/input', 'POST', { type: 'button', button: 'left', pressed: true })).status, 202);
  assert.equal((await request('/api/input', 'POST', { type: 'button', button: 'left', pressed: false })).status, 202);
  await delay(150); assert.equal((await native()).child_events, childEvents, 'parent change invalidates the hovered hidden child before wheel/button input');
  const readKey = await createToken(root, ['desktop.view']);
  const writeKey = await createToken(root, ['desktop.control']);
  assert.equal((await request('/api/workspaces', 'GET', undefined, writeKey)).status, 403);
  assert.equal((await request('/api/control', 'POST', { op: 'switchworkspace', workspace: 1 }, readKey)).status, 403);
  assert.equal((await request('/api/control', 'POST', { op: 'switchworkspace', workspace: 1 }, writeKey)).status, 202);
  await wait('control-only HTTP switch', async () => (await api('/api/workspaces')).active === 1);
  await switchTo(4);
  const mcp = async auth => {
    let session, sequence = 0;
    const rpc = (method, params, notify = false) => fetch(origin + '/mcp', { method: 'POST', headers: { Authorization: 'Bearer ' + auth, 'Content-Type': 'application/json', Accept: 'application/json, text/event-stream', ...(session && { 'Mcp-Session-Id': session }) }, body: JSON.stringify({ jsonrpc: '2.0', ...(!notify && { id: ++sequence }), method, params }) });
    const init = await rpc('initialize', { protocolVersion: '2025-03-26', capabilities: {}, clientInfo: { name: 'workspace-check', version: '1' } });
    session = init.headers.get('mcp-session-id'); assert(session); await init.text();
    await (await rpc('notifications/initialized', {}, true)).text();
    return async (name, args = {}) => {
      const body = await (await rpc('tools/call', { name, arguments: args })).text();
      const line = body.split('\n').find(l => l.startsWith('data:') && l.slice(5).trim());
      const response = JSON.parse(line ? line.slice(5) : body);
      assert(response.result, body); return response.result;
    };
  };
  const readMcp = await mcp(readKey), writeMcp = await mcp(writeKey);
  assert(!(await readMcp('workspaces')).isError);
  assert.equal((await writeMcp('workspaces')).isError, true);
  assert.equal((await readMcp('switch_workspace', { workspace: 1 })).isError, true);
  assert(!(await writeMcp('switch_workspace', { workspace: 1 })).isError);
  await wait('control-only MCP switch', async () => (await api('/api/workspaces')).active === 1);
  assert(!(await writeMcp('move_to_workspace', { window: animated.id, workspace: 2 })).isError);
  await wait('MCP family move', async () => (await info(animated.id)).workspace === 2 && (await info(dialog.id)).workspace === 2);
  assert((await writeMcp('switch_workspace', { workspace: 5 })).isError);
  await control({ op: 'movetoworkspace', id: animated.id, workspace: 3 });
  await switchTo(4);
  const readonly = await connect(undefined, readKey);
  const participant = await connect();
  sendControl(readonly, { op: 'switchworkspace', workspace: 1 });
  sendControl(participant, { op: 'switchworkspace', workspace: 1 });
  sendControl(participant, { op: 'movetoworkspace', id: animated.id, workspace: 1 });
  await delay(150); assert.equal((await api('/api/workspaces')).active, 4); assert.equal((await info(animated.id)).workspace, 3);
  sendControl(participant, { op: 'activate', id: animated.id });
  await wait('participant explicit activation', async () => (await api('/api/workspaces')).active === 3);
  sendControl(stream, { op: 'switchworkspace', workspace: 4 });
  await wait('window socket workspace control', async () => (await api('/api/workspaces')).active === 4);
  const switchStart = Date.now(), framesBeforeSwitch = desktop.frames;
  sendControl(desktop, { op: 'switchworkspace', workspace: 1 });
  await wait('controller switch broadcast', () => sockets.every(s => s.workspaces.active === 1));

  await wait('complete desktop frame after switch', () => desktop.frames > framesBeforeSwitch);
  console.log('Switch-to-desktop-frame ms:', Date.now() - switchStart);

  await exec('wayland-scanner', ['client-header', '/usr/share/wayland-protocols/staging/ext-workspace/ext-workspace-v1.xml', root + '/ext-workspace-v1-client-protocol.h']);
  await exec('wayland-scanner', ['private-code', '/usr/share/wayland-protocols/staging/ext-workspace/ext-workspace-v1.xml', root + '/ext-workspace-v1-protocol.c']);
  await exec('cc', ['-Wall', '-Wextra', '-Werror', '-I' + root, '/src/web/checks/workspace-panel.c', root + '/ext-workspace-v1-protocol.c', '-lwayland-client', '-o', root + '/panel']);
  await control({ op: 'spawn', cmd: `${root}/panel 2 > ${root}/panel.json` });
  await wait('panel protocol activation', async () => { try { return JSON.parse(await readFile(root + '/panel.json', 'utf8')).active === 2; } catch { return false; } });
  assert.deepEqual(JSON.parse(await readFile(root + '/panel.json', 'utf8')), { before: 1, active: 2, count: 4, commit_boundary: true });
  await wait('panel shared state', () => sockets.every(s => s.workspaces.active === 2));
  for (const client of sockets) client.socket.close();
  await wait('sockets closed', () => sockets.every(s => s.socket.readyState === WebSocket.CLOSED));

  browser = await chromium.launch({ executablePath: '/usr/bin/chromium', args: ['--no-sandbox'] });
  const page = await browser.newPage({ viewport: { width: 1100, height: 750 } });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(origin + '/#token=' + token);
  await page.waitForFunction(() => elsewhere.store.get().role === 'controller');
  const moveSelector = page.getByRole('combobox', { name: 'Move WorkspaceAnimation to workspace', exact: true });
  await moveSelector.selectOption('4');
  await wait('viewer family move', async () => (await info(animated.id)).workspace === 4 && (await info(dialog.id)).workspace === 4);
  await moveSelector.selectOption('3');
  await wait('viewer family move back', async () => (await info(animated.id)).workspace === 3);
  await page.screenshot({ path: root + '/workspace-viewer.png' });
  await page.setViewportSize({ width: 400, height: 750 });
  await page.screenshot({ path: root + '/workspace-narrow.png' });
  const headerFits = await page.locator('header').first().evaluate(el => el.scrollWidth <= el.clientWidth);
  assert(headerFits, 'workspace toolbar fits narrow viewport');
  await page.setViewportSize({ width: 1100, height: 750 });
  await page.getByRole('combobox', { name: 'Workspace', exact: true }).selectOption('1');
  await wait('viewer selector', async () => (await api('/api/workspaces')).active === 1);
  const reader = await browser.newPage();
  await reader.goto(origin + '/#token=' + readKey);
  await reader.waitForFunction(() => elsewhere.store.get().workspaces.active === 1);
  assert(await reader.getByRole('combobox', { name: 'Workspace', exact: true }).isDisabled());
  await page.getByRole('combobox', { name: 'Workspace', exact: true }).selectOption('2');
  await reader.waitForFunction(() => elsewhere.store.get().workspaces.active === 2);
  await reader.reload(); await reader.waitForFunction(() => elsewhere.store.get().workspaces.active === 2);
  const popup = await browser.newPage();
  await popup.goto(origin + '/?window=' + animated.id + '#token=' + token);
  await popup.getByRole('button', { name: 'Activate on Desktop', exact: true }).waitFor();
  await popup.bringToFront(); await popup.locator('canvas.stage').click(); await delay(200);
  await popup.evaluate(() => { elsewhere.store.set({ workspaces: { active: 3, count: 4 } }); window.dispatchEvent(new Event('focus')); });
  await delay(150);
  await popup.evaluate(() => elsewhere.store.set({ workspaces: { active: 2, count: 4 } }));
  assert.equal((await api('/api/workspaces')).active, 2, 'viewing and clicking hidden stream does not activate its desktop');
  await popup.getByRole('button', { name: 'Activate on Desktop', exact: true }).click();
  await wait('explicit viewer activation', async () => (await api('/api/workspaces')).active === 3);
  assert.deepEqual(errors, []);
  console.log('Panel commit boundaries, shared/replayed viewer state, grants, transient families, held-key release, hidden animated streams, and explicit viewer activation passed.');
  console.log('Four workspaces: placement, focus, movement, minimization, activation, hidden rendering, snapshots, and inactive input passed for Wayland and X11.');
} catch (error) { console.error((await readFile(root + '/server.log', 'utf8')).split('\n').slice(-12).join('\n')); throw error; }
finally {
  for (const client of sockets) client.socket.close();
  await browser?.close();
  if (server.exitCode === null) { server.kill('SIGTERM'); await new Promise(r => server.once('exit', r)); }
  await log.close();
  if (!process.env.KEEP_FIXTURE) await rm(root, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 }); else console.log(root);
}
